### ISSUE TITLE
Request: No Default Keymaps

### ISSUE THREAD

**Issue by Drew-Daniels** [Funk66/jira.nvim#2]
Would be nice if the keymaps of `<leader>jv` and `<leader>jo` were not automatically set with this plugin - so users could choose their own keymaps for the `open_issue` and `view_issue` functions. Or, if we were given an option to substitute these keymaps for other ones within the `setup` function

**Comment by Funk66** [comment]
Thanks. It was one of those things I didn't do because I wasn't expecting this repo to get any attention. Let me know if there's anything else you would like me to improve.

**Comment by Drew-Daniels** [comment]
No thank you. This plugin has been really helpful for my note-taking workflow with [neorg](https://github.com/nvim-neorg/neorg). Maybe something else will come to mind the more I use it
